CREATE TABLE IF NOT EXISTS "User" (
  "IdUser" SERIAL PRIMARY KEY,
  "User" VARCHAR(45) NOT NULL,
  "Role" VARCHAR(45) NOT NULL,
  "Password" VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS Product (
  "idProduct" SERIAL PRIMARY KEY,
  "Product" VARCHAR(45) NOT NULL,
  "Imagem" VARCHAR(45) NOT NULL,
  "Category" VARCHAR(45) NOT NULL
);

CREATE OR REPLACE VIEW view1 AS SELECT 1 AS id;